import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import './ResultCards.css';
export const CarResultCard = ({ car }) => {
    return (_jsxs("div", { className: "travels-result-card", children: [_jsxs("div", { className: "travels-result-content", children: [_jsxs("h3", { className: "travels-result-title", children: [car.vehicle.make, " ", car.vehicle.model || car.category] }), _jsx("div", { className: "travels-result-subtitle", children: car.vendor }), _jsxs("div", { className: "travels-car-specs", children: [_jsxs("span", { children: ["\uD83D\uDE97 ", car.vehicle.type] }), _jsxs("span", { children: ["\uD83D\uDC65 ", car.vehicle.passengers, " passengers"] }), _jsxs("span", { children: ["\uD83E\uDDF3 ", car.vehicle.luggage, " bags"] }), _jsxs("span", { children: ["\u2699\uFE0F ", car.vehicle.transmission] })] }), car.features.length > 0 && (_jsx("div", { className: "travels-result-amenities", children: car.features.map((feature, i) => (_jsx("span", { className: "travels-amenity-tag", children: feature }, i))) })), _jsxs("div", { className: "travels-car-location", children: ["\uD83D\uDCCD Pickup/Dropoff: ", car.location.pickup] }), _jsxs("div", { className: "travels-car-mileage", children: ["\uD83D\uDEE3\uFE0F ", car.mileage] })] }), _jsxs("div", { className: "travels-result-action", children: [_jsxs("div", { className: "travels-result-price", children: [_jsxs("span", { className: "travels-price-amount", children: ["$", car.price.amount.toFixed(0)] }), _jsx("span", { className: "travels-price-unit", children: "total" })] }), _jsx("a", { href: car.affiliateUrl, target: "_blank", rel: "noopener noreferrer", className: "travels-book-btn", children: "View on Expedia" })] })] }));
};
export const ActivityResultCard = ({ activity }) => {
    const hours = Math.floor(activity.duration / 60);
    const minutes = activity.duration % 60;
    const durationText = hours > 0
        ? `${hours}h ${minutes > 0 ? `${minutes}m` : ''}`
        : `${minutes}m`;
    return (_jsxs("div", { className: "travels-result-card", children: [activity.images.length > 0 && (_jsxs("div", { className: "travels-result-image", children: [_jsx("img", { src: activity.images[0], alt: activity.name }), _jsx("div", { className: "travels-result-badge", children: activity.category })] })), _jsxs("div", { className: "travels-result-content", children: [_jsx("h3", { className: "travels-result-title", children: activity.name }), _jsxs("div", { className: "travels-result-location", children: ["\uD83D\uDCCD ", activity.location.name] }), activity.rating && (_jsxs("div", { className: "travels-result-rating", children: ["\u2B50 ", activity.rating.toFixed(1), activity.reviewCount && (_jsxs("span", { className: "travels-result-reviews", children: ["(", activity.reviewCount.toLocaleString(), " reviews)"] }))] })), _jsxs("div", { className: "travels-activity-duration", children: ["\u23F1\uFE0F Duration: ", durationText] }), activity.highlights.length > 0 && (_jsx("div", { className: "travels-activity-highlights", children: activity.highlights.slice(0, 3).map((highlight, i) => (_jsxs("div", { className: "travels-highlight", children: ["\u2713 ", highlight] }, i))) })), _jsx("div", { className: "travels-activity-policy", children: activity.cancellationPolicy })] }), _jsxs("div", { className: "travels-result-action", children: [_jsxs("div", { className: "travels-result-price", children: [_jsxs("span", { className: "travels-price-amount", children: ["$", activity.price.amount.toFixed(0)] }), _jsx("span", { className: "travels-price-unit", children: "per person" })] }), _jsx("a", { href: activity.affiliateUrl, target: "_blank", rel: "noopener noreferrer", className: "travels-book-btn", children: "View on Expedia" })] })] }));
};
